runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup).*
  script: blog.wsgi.application
  login: admin

- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: blog.wsgi.application


skip_files:
    - manage.py
    - README.md
    - install_deps
    - prod.txt
    - sitepackages/dev*
    - \.storage.*
    - \.git
    - (.*)\.pyc