# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 11:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contenttype',
            managers=[
                ('None', django.db.models.manager.Manager()),
            ],
        ),
    ]
